# Generated by Django 5.0 on 2023-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=250, verbose_name='Nombres de autor')),
                ('apellidos', models.CharField(max_length=250, verbose_name='Apellidos de autor')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='x')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Desactivado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
    ]
